title: Fred's Homepage
page-top-title: Fred Oliveira
top-section-bg-text: Computer Science | Artificial Intelligence
home-subtitle: Fred Oliveira
copyright-text: '&copy; Fred 2024-2025. All Rights Reserved.'
