title: Fred's Homepage
page-top-title: Frederico Santos de Oliveira
top-section-bg-text: Computer Science | Artificial Intelligence
home-subtitle: Frederico Santos de Oliveira
copyright-text: '&copy; Fred 2024-2025. All Rights Reserved.'
